apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: devops-example-working
  namespace: example-services
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: devops-example-working
